# Generated by Django 3.0.7 on 2021-09-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_no',
            field=models.CharField(default='00000023ee', max_length=200),
            preserve_default=False,
        ),
    ]
