# Generated by Django 3.0.7 on 2021-09-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_registration_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='0749303894', max_length=200),
            preserve_default=False,
        ),
    ]
