# Generated by Django 3.0.7 on 2021-10-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210930_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
