# Generated by Django 3.0.7 on 2021-10-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_skillset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skill',
        ),
        migrations.AlterField(
            model_name='skillset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.User'),
        ),
    ]
