# Generated by Django 3.0.7 on 2021-10-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211015_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reg_document',
            field=models.FileField(blank=True, null=True, upload_to='media/docs/'),
        ),
    ]
