# Generated by Django 3.0.7 on 2021-12-08 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_reg_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
