# Generated by Django 3.0.7 on 2021-12-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20211208_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='academic_qualification',
            field=models.CharField(choices=[('PhD', 'PhD'), ('Masters', 'Masters'), ('Degree', 'Degree'), ('Diploma', 'Diploma'), ('A_Level_Certificate', 'A_Level_Certificate'), ('O_Level_Certificate', 'O_Level_Certificate'), ('Primary_Certificate', 'Primary_Certificate'), ('Still_Studying', 'Still_Studying'), ('None', 'None')], default='Degree', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=8),
        ),
    ]
