# Generated by Django 3.0.7 on 2021-12-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20211208_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='residence',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_preference',
            field=models.CharField(choices=[('full', 'Full Time'), ('part', 'Part Time'), ('freelance', 'Freelance')], default='Full Time', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('1', 'Executive Level'), ('2', 'Manager Level'), ('3', 'Mid Level'), ('4', 'Junior Level'), ('5', 'Beginner Level')], default='Beginner Level', max_length=30),
        ),
    ]
