# Generated by Django 3.0.7 on 2021-12-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20211209_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, error_messages={'required': 'Role must be provided'}, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='terms_and_conditions',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='working_experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
