# Generated by Django 3.0.7 on 2021-12-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='industry',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, default='media/default/avatar.png', null=True, upload_to='media/avatars/'),
        ),
    ]
