# Generated by Django 3.0.7 on 2021-12-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20211210_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
