# Generated by Django 3.0.7 on 2022-01-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20211217_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='terms_and_conditions',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
