# Generated by Django 3.0.7 on 2022-01-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20220103_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='terms_and_conditions',
            field=models.BooleanField(default=False),
        ),
    ]
