# Generated by Django 3.0.7 on 2021-10-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0015_job_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
