# Generated by Django 3.0.7 on 2021-12-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0021_auto_20211213_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='website',
        ),
    ]
