# Generated by Django 3.0.7 on 2021-12-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0022_remove_job_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_image',
            field=models.FileField(blank=True, null=True, upload_to='media/jobs/'),
        ),
    ]
