# Generated by Django 3.0.7 on 2021-12-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_company_website_url'),
        ('jobsapp', '0023_job_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skill',
            field=models.ManyToManyField(blank=True, to='accounts.Skillset'),
        ),
    ]
