# Generated by Django 3.0.7 on 2021-12-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0025_auto_20211217_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='skills',
            new_name='skill',
        ),
    ]
