# Generated by Django 3.0.7 on 2021-12-22 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0032_auto_20211217_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_image',
            field=models.FileField(blank=True, null=True, upload_to='jobs'),
        ),
        migrations.AddField(
            model_name='resume',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobsapp.JobCategory'),
        ),
    ]
