# Generated by Django 3.0.7 on 2021-12-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0033_auto_20211222_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='category',
        ),
    ]
